version: '3.8'

services:
  wine-runner:
    build: .
    container_name: wine_runner_container
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - DBFOLDER=acc001
      - TZ=Asia/Bangkok
    command: wine main333111.exe
