version: '3.8'

services:
  exe_runner:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DBFOLDER=${DBFOLDER}
      - EXE_NAME=${EXE_NAME}
    command: sh -c "wine \$EXE_NAME"
